name: DungeonGenerator
main: com.PoolNoodL.Main
version: 1.0
author: PoolNoodL
api-version: 1.16
commands:
  generate:
    description: generates a custom dungeon.
    usage: /<command>
    aliases: [dungeon, generatedungeon]
  lobby:
    description: returns player to lobby
    usage: /<command>
    aliases: [ l, return ]